src/index.js
We forgot one thing. Need to set indexLatest when using the index prop. You can see the bug if you remove the height on the tab example and make one of the tabs taller.
=> Set index latest when passing index prop

src/index.js
It seems like `display: 'flex'` still doesn't work in Safari
And can be fixed by adding `display: '-webkit-box'` according to this trick: https://css-tricks.com/using-flexbox/
But inline style in react didn't support same key with different value, https://github.com/facebook/react/issues/2020, hence this weird hack. (This approach has also been used in material-ui: https://github.com/callemall/material-ui/pull/1226/files)
=> Fix flexbox styling in Safari

.gitignore, README.md, src/index.js
1、update `.gitignore` to ignore webstorm configuration files
2、add `onSwitching` callback on slide switching
3、add a second parameter `fromIndex` for `onChangeIndex` so that we know which index the slide came from.
4、update README
=> add `onSwitching` callback on slide switching

src/index.native.animated.js, src/index.native.scroll.js
Requiring React API from react-native is now deprecated in 0.25.
=> Update for React Native 0.25

src/index.native.animated.js
a movement of greater than 3 in the x direction prevents swipe
from taking precedence over tap events
=> increasing onMoveShouldSetPanResponder threshold for swipe

src/utils/getDisplaySameSlide.js
I got this issue when the item got removed.
=> Check if the child item are there before calling the `key` property

src/SwipeableViews.js, src/SwipeableViews.spec.js
I found the need to use a class name on the slide component since I use responsive media queries in CSS for the slides.
Instead of using a selector such as .sliderRoot>div>div - I rather just apply a className to the slides.
I hope the added test is enough to make this a simple  PR to merge.
=> add support for a 'slideClassName' prop

packages/react-swipeable-views/src/SwipeableViews.js, packages/react-swipeable-views/src/SwipeableViews.spec.js
Currently the 'transform' uses a prefix for the actual transform value but not for the transition property and I needed this change in order for animated transitions to work in Safari in iOS 8.3. 
One other thing to note is that it wasn't working with multiple transition properties, such as:
```css
-webkit-transition: transform 1s, -webkit-transform 1s;
```
This is why I've just got '-webkit-transform' under '-webkit-transition' and 'transform' under 'transition'.
=> -webkit prefix should be used for transform property in -webkit-transition 

packages/react-swipeable-views/src/SwipeableViews.js
Gracefully handles a rootNode reference equaling null.
I am a big fan of this repo (thanks for the awesome work!) and react-virtualized.
I often use the react-virtualized infinite scroller inside of the swipeable views component.
As a result, I can get to pretty large lists calling rerender fairly often while running inside of this component. 
Combining that with running inside a webview on Apache Cordova on iOS (I know we should be using native, but we're already a bit too far down a road here), and it seems like we can get to a small window where the old ref element has been expired and set to null, but the new ref element hasn't been assigned yet.
If this occurs while any of the touchstart events are fired, the page breaks from an uncaught exception emitted by the swipeable views …
=> (fix) Handle rootNode ref loss gracefully

docs/src/Main.js, docs/src/demo/DemoRtl.js, packages/react-swipeable-views/src/SwipeableViews.js, packages/react-swipeable-views/src/SwipeableViews.spec.js
This is quite a hacky workaround. A proper fix would read the direction style computed with `getComputedStyle` and `getPropertyValue` and use the right logic. For now, it's doing the job.
Plus, I don't want to complexify the codebase for a use case I don't have.
Closes #243
=> [docs] Add an example for handling RTL

packages/react-swipeable-views/src/SwipeableViews.js
Before #239 `onTouchMove` was not listened when `disabled` property was enabled. This PR restores the behaviour by returning early from `handleTouchMove`. It fixes situations where swiping causes slides to partially slide in and get stuck when swiping should be disabled.
=> fix(browser): Bail out from handleTouchMove if 'disabled' property is enabled.

README.md
Replaced overscanSlideCount with overscanSlideAfter and overscanSlideBefore props.
=> Corrected virtualize HOC props in readme

package.json
It should be `private` property but your package is public and it should have `false` value (it's the default).
=> Fix typo in package.json.

packages/react-swipeable-views/src/SwipeableViews.js
Hi,
I have some loading images in slides.. with fade in animation..  and I was getting some random jumps during the slide transitions (suddenly jumped to the end of the transition) and I isolated that its because  TransitionEnd event which bubbles up to the Container and triggers `handleTransitionEnd()` sooner.
Checking if the event is coming from container should be reliable solution to this.
=> Ignore TransitionEnd events from children

packages/react-swipeable-views/src/SwipeableViews.js
I have tested the change on Firefox 57 with no issue :).
Revert 1605c624
Closes #380
=> [performance] Add willChange property

packages/react-swipeable-views-utils/src/virtualize.js
Currently, we pass the onTransitionEnd prop directly to MyComponent which means that whatever function we pass into the onTransitionEnd prop gets called directly by the Swipeable component. The bug here is that the virtualize() handleTransitionEnd function never gets called, so we do not call setWindow() and we keep adding swipeable views without unmounting any. Correct behavior is to either move the {...other} assignment to be before assigning the onTransitionEnd prop under My Component, or removing the onTransitionEnd prop from {...other} through destructive assignment, which makes more sense.
=> [virtualize] Fix onTransitionEnd call

packages/react-swipeable-views/src/SwipeableViews.js
Great library! I'm the maintainer of [react-swipeable](https://github.com/dogfessional/react-swipeable) and just wanted to see how this library handled some things and noticed these could get "cleaned up" 😸 
- update ref assignment inline functions to use class methods
- avoids new function creation on each render
- avoids `null` assignments
- https://reactjs.org/docs/refs-and-the-dom.html#caveats-with-callback-refs
~Could probably clean up these lines too after/with this PR:
https://github.com/oliviertassinari/react-swipeable-views/blob/master/packages/react-swipeable-views/src/SwipeableViews.js#L359-L363~
- cleaned up `null` checks 😸 
Let me know, cheers!
=> Improve ref performance

packages/react-swipeable-views/src/SwipeableViews.js, packages/react-swipeable-views/src/SwipeableViews.spec.js
```console
$ yarn test:unit
yarn run v1.7.0
$ cross-env NODE_ENV=test mocha
․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․!․․․․․․․․․․․․․․․․
69 passing (2s)
1 failing
1) SwipeableViews
prop: animateTransitions
should not use a spring if animateTransitions is false:
TypeError: Cannot read property 'displaySameSlide' of undefined
at SwipeableViews.handleTransitionEnd (packages/react-swipeable-views/src/SwipeableViews.js:647:20)
at SwipeableViews.setIndexCurrent (packages/react-swipeable-views/src/SwipeableViews.js:327:12)
at new SwipeableViews (packages/react-swipeable-views/src/SwipeableViews.js:234:10)
at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:131:26)
at /Users/ykzts/works/ykzts/react-swipeable-views/node_modules/e …
```
=> Initialize this.state before calling setIndexCurrent

packages/react-swipeable-views-utils/src/virtualize.js, packages/react-swipeable-views/src/SwipeableViews.js, packages/react-swipeable-views/src/SwipeableViews.test.js
I've been using this fix in production for a few weeks. It worked well and I didn't need to do any other fix after the change. 
Closes #453 
To be honest, I am not familiar with enzyme, especially how lifecycle and first render/second render works in it.
I am confused by how the test 'prop: disableLazyLoading' was written. Does it mean mounting the same component twice in consecutive tests will count as first render and then second render?
I'd really like some suggestions on that, I tried some fixes just to pass the test.
=> Fix lazy loading

docs/src/modules/components/AppDrawer.js, docs/src/pages/getting-started/supported-platforms.md, packages/react-swipeable-views/.npmignore, packages/react-swipeable-views/dist/legacy-browser-support.css, packages/react-swipeable-views/src/SwipeableViews.js
Fixes https://github.com/oliviertassinari/react-swipeable-views/issues/465
I think there's not much harm to keeping around the CSS, but keeping it in a separate distributed file, such that people who need to support older browsers can just include the CSS themselves.
Strikes a nice mix of avoiding cruft for sites that only support modern browsers, while maintaining a CSP-friendly way of adding in support for legacy browsers.
Thoughts?
=> Pull out legacy browser support CSS

packages/react-swipeable-views-utils/src/autoPlay.js, packages/react-swipeable-views-utils/src/autoPlay.test.js
Fixes #508 by pausing the autoPlay animation if the document is hidden, using the Page Visibility API.
=> Pause autoPlay when the window is hidden

packages/react-swipeable-views-utils/package.json
Fixes `➤ YN0002: │ react-swipeable-views-utils@npm:0.13.3 doesn't provide react@^16.3.0 requested by react-event-listener@npm:0.6.6` using `yarn@2.0.0-rc.1`
More context in https://github.com/yarnpkg/berry/issues/3
=> fix(react-swipeable-views-utils): Missing peer dep warning in yarn v2

packages/react-swipeable-views/src/SwipeableViews.js
Issue:
- If you add padding to the container (i.e. to
preview prev & next items), then the swype gesture
will show a gap between finger position and
the slides moving.
- While handleSwipeStart takes into account the viewport paddings,
handleSwipeMove did not.
This solves #444
=> Fix padding while swiping

packages/react-swipeable-views-utils/src/virtualize.js
When using virtualize HOC, child slides are not re-rendered whenever their props change.
[Demo](https://codesandbox.io/s/material-demo-l54hy)
See [React.PureComponent](https://reactjs.org/docs/react-api.html#reactpurecomponent):
> ... Furthermore, React.PureComponent’s shouldComponentUpdate() skips prop updates for the whole component subtree. Make sure all the children components are also “pure”.
Besides that, [autoPlay](https://github.com/oliviertassinari/react-swipeable-views/blob/v0.13.3/packages/react-swipeable-views-utils/src/autoPlay.js) and [bindKeyboard](https://github.com/oliviertassinari/react-swipeable-views/blob/v0.13.3/packages/react-swipeable-views-utils/src/bindKeyboard.js) do not use PureComponent.
=> Switch virtualize hoc parent from PureComponent to Component

native/packages/react-swipeable-views-native/src/SwipeableViews.scroll.tsx
This prevents a number of swipe transition issues in React Native. 
1) When swiping left quickly on slide index 0, the index often falls below. eg: -0.00257788, and the same when you swipe past the slide list length, eg. 6.05.
2) Swiping between slides sometimes leave a stuck transition, or slightly off alignment. Again, because of floating point indexes.
This came about when setting a separate category list, based on the index, and then updating the component using the index={this.state.category}. Reason is that I can then also select a category from the dropdown, and it goes to the correct slide. i'd assume this could be a pretty common use case. 
Screen captures: 
Issue: https://drive.google.com/open?id=13j_1n9PBFlm5yViA4290AUHT70VWL-Tk
Resolved: …
=> Round indexes to whole numbers

packages/react-swipeable-views/src/SwipeableViews.js
This PR is a fix to the container (view) height not updating itself after it receives new children.  
Here is the [original issue](https://github.com/oliviertassinari/react-swipeable-views/issues/535).
Personally I don't want this container height update to be animated so I'll remove that in my fork. But I think you want to keep that animation mandatory there so this PR doesn't touch that.
=> Update height when receiving new children

packages/react-swipeable-views/src/SwipeableViews.js
In addition to PR opened by @tuomohopia, this PR fixes a problem of the container height not being updated when a browser window is resized (the problem manifests itself when `animateHeight` prop is set to true).
=> Update height when window is being resized

packages/react-swipeable-views/package.json, yarn.lock
This is for #542 
I believe #542 is related to the current issue that I have:
```bash
ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/addClass'
ERROR in ./node_modules/react-transition-group/esm/CSSTransition.js
Module not found: Error: Can't resolve 'dom-helpers/removeClass'
```
=> Update dom-helpers dependency

packages/react-swipeable-views/src/SwipeableViews.js
Hi,
I'd like to discuss this little change because we have a specific use case that can only be solved reliably by doing this, as far as I can tell. 
The idea here is that if we return something _truthy_ the swipe will be prevented.
The use case is that we have a virtualized list inside the swipe container... so the component cannot detect that the list is scrolling (indeed because there's no _real_ scroll), and it swipes even if we still have scroll in the list... 😅 
The other approach would be to set the `disabled` prop dynamically with `setState()`, but it's junky/buggy because we can swipe up and down even outside the list container. Imagine that inside the swipe container we have 1) an header with a fixed height plus 2) a virtual list with scroll, so if:
- we swipe up (y axis, …
=> Add possibility to prevent swipe dinamically i.e. short-circuit inside onTouchStart()

babel.config.js, packages/react-swipeable-views-core/package.json, packages/react-swipeable-views-utils/package.json, packages/react-swipeable-views/package.json
We don't have to use the same version of `@babel/runtime` as `@babel/plugin-transform-runtime`. We can pin to whatever version we like as long as [`transform-runtime` is configured accordingly](https://babeljs.io/docs/en/babel-plugin-transform-runtime#version).
=> feat: Pin `@babel/runtime` to major

package.json, packages/react-swipeable-views/src/SwipeableViews.js, yarn.lock
For the same reasons as described in #567 I cannot make this package build. (error with static class properties despite babel seems to have the correct plugin to handle them).
I also have an issue with `workspaces` in the `package.json` file (same error as in CI tests results) It works when I set `private` to `true`. I tried removing `workspaces`declaration in the `package.json` file as it's already configured in lerna config, but it also does not work. Not sure how to solve this...
I still have pushed some code that should resolve the ([undocumented](https://github.com/react-bootstrap/dom-helpers/issues/77)) breaking changes in `dom-helpers` v5 vs v3
I can't test/build, but I wanted to share this, as I think it should solve the import issues.
=> [Help needed] Update dom-helpers related code to fix  import errors

packages/react-swipeable-views/package.json, packages/react-swipeable-views/src/SwipeableViews.js
@oliviertassinari here is the patch without `dom-heplers`. 
I just use native events, based on:
1. [MUI `.browserlistrc` file](https://github.com/mui-org/material-ui/blob/012747e529bbbd0ea37e7dc26acda5e92fbe5ec1/.browserslistrc)
2. [`addEventListner` CanIUse support table](https://caniuse.com/#search=addeventlistener)
3. [CSS Transitions (incl. `transitionend` event) CanIUse support table](https://caniuse.com/#feat=css-transitions)
Does that work?
Closes #564
=> Use native event listeners instead of dom-heplers shims

packages/react-swipeable-views-utils/package.json, packages/react-swipeable-views-utils/src/autoPlay.js, yarn.lock
Replaces [`fbjs/lib/shallowEqual`](https://www.npmjs.com/package/fbjs) with [`shallow-equal`#`shallowEqualObjects`](https://www.npmjs.com/package/shallow-equal).
`fbjs` is not intended for usage outside of facebook and pulls in outdated dependencies (e.g. `isomorphic-fetch`).
It doesn't use same-value equality as of yet (proposed in https://github.com/moroshko/shallow-equal/pull/17) but it seems like this isn't an issue here since we control what kind of values we compare.
=> feat: use shallow-equal over fbjs

README.md
The links to API and the other ones are inside of the demo page. That is good because it exists but could have a shortcut to make life easier.
=> Make easier to find the Component API docs

packages/react-swipeable-views/src/SwipeableViews.js
Repro:
- Put a portal inside a swipeable view
- click & drag something in the portal
- watch the `while` loop propagate up to the `html` tag & bork the app because `html.hasAttribute` isn't a function
Closes #589
=> Fix throw error when using a portal inside a view

docs/src/pages/demos/DemoAnimateHeight.js, docs/src/pages/demos/DemoAutoPlay.js, docs/src/pages/demos/DemoAxis.js, docs/src/pages/demos/DemoCircular.js, docs/src/pages/demos/DemoCoverflow.js, docs/src/pages/demos/DemoHocs.js, docs/src/pages/demos/DemoKeyboard.js, docs/src/pages/demos/DemoNested.js, docs/src/pages/demos/DemoResistance.js, docs/src/pages/demos/DemoRtl.js, docs/src/pages/demos/DemoScroll.js, docs/src/pages/demos/DemoTabs.js, docs/src/pages/demos/DemoVirtualize.js, docs/src/pages/demos/DemoWidth.js
This PR enables mouse events on all swipeableView demos, allowing a user to try them out without needing a device with touch capabilities.
=> Enable mouse events on all demos

packages/react-swipeable-views-utils/src/autoPlay.js, packages/react-swipeable-views-utils/src/autoPlay.test.js, packages/react-swipeable-views-utils/src/bindKeyboard.js, packages/react-swipeable-views-utils/src/bindKeyboard.test.js, packages/react-swipeable-views-utils/src/virtualize.js, packages/react-swipeable-views-utils/src/virtualize.test.js
=> Fix autoPlay HOC swallowing third parameter of onChangeIndex

packages/react-swipeable-views/src/SwipeableViews.js
On some browsers, I have scrolled to the bottom, but the calculated "areNotAtEnd" value is true, so I can't continue to swipe next.
https://github.com/jquery/api.jquery.com/issues/608
=> Fix scrollTop is not always be an integer

packages/react-swipeable-views/package.json
This PR addresses the version issue when using react-swipeable-views in a project with `"react": "^17.0.1"` as dependency and running `npm install`:
```
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.3.0 || ^16.0.0" from react-swipeable-views@0.14.0-alpha.0
npm ERR! node_modules/react-swipeable-views
npm ERR!   react-swipeable-views@"^0.14.0-alpha.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
Reproducible with Node.js `v14.16.0` and npm `v7.6.1`.
=> Adjust react version in peerDependencies
