oliviertassinari/react-swipeable-views

package.json
src/index.js

Hey just cleaned up the code a bit cuz I was using this on a project. Also took care of that React 0.14.0 related warning.

Fix React 0.14.0 warning about findDomNode.

---

README.md
src/index.js

I'd like to be able to stop the user from navigating slides if needed

Prop for disabling touch events

---

docs/src/Main.jsx
src/index.js

For #6. Let me know what you think

Support dynamic height container

---

src/index.js

Should fix https://github.com/oliviertassinari/react-swipeable-views/issues/19 and potential incorrect height.

Improve auto height

---

README.md
src/index.js

Hello, and thanks for the awesome component you have made!
We would need to be able to style the slide component, so I made a modification to the source which allows user to pass inline styles for the slide as props.
BR,
Ville Miekk-oja

Prop for inline styling of slide component

---

README.md

I added typescript definitions for your library.

DefinitelyTyped.org badge

---

src/SwipeableViews.js
src/index.native.animated.js
src/index.native.scroll.js

Fix https://github.com/oliviertassinari/react-swipeable-views/issues/56.

[API] Be more consitent

---

src/SwipeableViews.js
src/index.native.animated.js

Fix https://github.com/oliviertassinari/react-swipeable-views/issues/95.

[index] Fix a regression

---

README.md

Close https://github.com/oliviertassinari/react-swipeable-views/issues/54.

[Docs] Document the usage of the auto play

---

README.md

This commit is for #104 
Thanks!

Update README to notify dependency of react-motion

---

src/index.native.animated.js

Closes https://github.com/oliviertassinari/react-swipeable-views/pull/107.

[native] Added callbacks for onTouchStart and onTouchEnd

---

README.md
src/SwipeableViews.js
src/SwipeableViews.spec.js
src/index.native.animated.js
src/index.native.scroll.js

Closes https://github.com/oliviertassinari/react-swipeable-views/issues/108.

[API] Standardize the animateTransitions boolean

---

src/SwipeableViews.js
src/SwipeableViews.spec.js
src/index.native.animated.js

Use https://github.com/oliviertassinari/react-swipeable-views/issues/114 as inspiration.
cc @funkyeah.

[Browser] Import the logic from the Native to the Browser platform

---

README.md

Awesome component by the way, thanks!

Small README typo

---

.eslintrc.js
.travis.yml
README.md
docs/src/Demo/Demo4.js
src/SwipeableViews.js
src/SwipeableViews.spec.js

This is a breaking change.
Closes #36.

[Browser] Add an animateHeight property

---

README.md
docs/src/Demo/Demo1.js
docs/src/Demo/Demo1.native.js
docs/src/Demo/Demo2.js
docs/src/Demo/Demo2.native.js
docs/src/Demo/Demo5.native.js
docs/src/Demo/Demo6.js
docs/src/Demo/Demo6.native.js
docs/src/Demo/Demo7.js
docs/src/Main.js
docs/src/Main.native.js
docs/src/demo/Demo7.native.js
docs/src/demo/Demo8.js
src/SwipeableViews.js
src/SwipeableViews.spec.js
src/constant.js
src/index.native.animated.js
src/index.native.scroll.js
src/utils/computeIndex.js
src/utils/computeIndex.spec.js

[Browser] Add an axis property

---

package.json

I added the dependencies to resolve the issue in https://github.com/oliviertassinari/react-swipeable-views/issues/129

fix dependencies with warning

---

docs/src/Demo/Demo6.js
src/SwipeableViews.js
src/SwipeableViews.spec.js
src/constant.js

Closes #132.
Closes #131.
Closes #26.

[scroll] Add better support for nested scroll

---

README.md
package.json

[npm] Explicit the dependencies for each platform

---

src/autoPlay.js
src/autoPlay.spec.js
src/bindKeyboard.js
src/bindKeyboard.spec.js

[HOC] Add the missing second argument of onChangeIndex

---

src/virtualize.js
src/virtualize.spec.js

@michaellopez Thanks for the original PR.
I have updated the test and the implementation.
Closes #166.

[HOC] Add the missing second argument of onChangeIndex to virtualize.

---

README.md
package.json
packages/react-swipeable-views/package.json
packages/react-swipeable-views/src/autoPlay.js
packages/react-swipeable-views/src/bindKeyboard.js
packages/react-swipeable-views/src/virtualize.js

[utils] Address the issue with the latest multi package migration

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[browser] Improve the accessibility support

---

packages/react-swipeable-views/package.json

Update dom-helpers dependency

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

fix(browser): block the thread when handling touch events

---

.flowconfig
package.json
packages/react-swipeable-views/src/SwipeableViews.js

feat(flow): add flow back to the project

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

Replace role="option" attr with data-swipeable.
Closes #245

Fix accessibility caused by aria roles

---

README.md
packages/react-swipeable-views/src/SwipeableViews.js

feat(browser): add a ignoreNativeScroll property

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

fix(scroll): fix scroll detection logic on the desktop

---

docs/src/demo/DemoHocs.js
docs/src/demo/DemoHocs.native.js
packages/react-swipeable-views-utils/src/virtualize.js
packages/react-swipeable-views-utils/src/virtualize.spec.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[virtualize] Add overscanSlideAfter and overscanSlideBefore

---

docs/src/demo/DemoAxis.js
packages/react-swipeable-views/src/SwipeableViews.js

This is a continuation of #251, thanks @jmheik for the original PR.
I have updated the demo to take into account your stress test. It's a nice one by the way 😄 .
I have taken what looks like reasonable changes in order to fix the failing demo.
Closes #251.

Fix native vertical scrolling within slide.

---

README.md
docs/src/demo/DemoSimple.js
packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[browser] Mouse events for swiping

---

docs/src/demo/DemoAnimateHeight.js
packages/react-swipeable-views/src/SwipeableViews.js

@Nopik Another shot at the issue. Let me know what you think.
I have updated the demo as a starting point for the documentation.
Closes #279.
Closes #177.

[Browser] Expose a slideUpdateHeight hook

---

packages/react-swipeable-views/src/SwipeableViews.js

fix(browser): trigger transitionEnd even if animateTransitions is false

---

packages/react-swipeable-views-native/src/SwipeableViews.animated.js

fix(native): fix the animated implementation inside a Modal

---

packages/react-swipeable-views/src/SwipeableViews.js

Fixes iss258

---

README.md
packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

I created this PR adding the api to disable lazyloading.
Sometimes it is necessary to render all the props.children (eg. server-side rendering)
Please review it:)

Add lazyloading api

---

package.json

Just a small typo in package.json

Fix command for npm start

---

.eslintignore
.eslintrc.js
packages/react-swipeable-views/package.json
packages/react-swipeable-views/src/SwipeableViews.js

- Closes #319
- Support React Fiber

[browser] Remove warnings and X

---

README.md
packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

Allow access to the updateHeight method through ref

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[browser] Fix action property

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[performance] Remove re-render on touchmove

---

.circleci/config.yml
.size-limit
README.md
package.json
yarn.lock

[core] Add size-limit

---

docs/src/pages/api/api.md
packages/react-swipeable-views-utils/src/autoPlay.js
packages/react-swipeable-views-utils/src/bindKeyboard.js
packages/react-swipeable-views-utils/src/virtualize.js
packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js

[SwipeableViews] Add meta argument to the onChangeIndex callback

---

README.md
docs/src/pages/getting-started/installation.md
package.json

[docs] Better document the bundle size implication

---

packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.spec.js
pages/index.js

[vertical] Fix scroll handling with vertical example

---

docs/src/pages/demos/DemoCircular.js
docs/src/pages/demos/demos.md
packages/react-swipeable-views-core/src/checkIndexBounds.js
packages/react-swipeable-views-core/src/getDisplaySameSlide.spec.js
packages/react-swipeable-views-core/src/mod.js
packages/react-swipeable-views/src/SwipeableViews.spec.js
pages/demos/demos.js

I have given up on the higher-level API. Let's start with documenting how to process.
Closes #181

[docs] Add a circular demo

---

docs/src/modules/components/AppWrapper.js
docs/src/modules/components/Demo.js
package.json
yarn.lock

Related to https://github.com/CompuIves/codesandbox-client/issues/263
*codepen -> codesandbox*

[docs] Add edit on codesandbox button

---

README.md

[docs] Fix demo link

---

README.md

[docs] Add a Who's using? section

---

README.md

[Tinder](https://tinder.com) swipes right on `react-swipeable-views` 🔥 
Thanks for the library! 💙

Tinder is using react-swipeable-views

---

packages/react-swipeable-views/src/SwipeableViews.js

[core] Fix typos

---

docs/src/modules/components/AppFrame.js
docs/src/modules/components/Link.js
docs/src/modules/components/withRoot.js
docs/src/modules/utils/find.js

[docs] Fix export

---

packages/react-swipeable-views-core/package.json
packages/react-swipeable-views-utils/package.json
packages/react-swipeable-views/package.json

[core] Fix @babel/runtime

---

docs/src/pages/api/api.md

[docs] Fix containerStyle description

---

native/packages/react-swipeable-views-native/package.json
native/packages/react-swipeable-views-native/src/SwipeableViews.animated.tsx
native/packages/react-swipeable-views-native/src/SwipeableViews.scroll.tsx

Fix warning require

---

native/app.json
native/packages/react-swipeable-views-native/README.md

add expo demo link

---

docs/src/pages/api/api.md

Docs for this change are missing: https://github.com/oliviertassinari/react-swipeable-views/pull/206/files

[docs] Add slideClassName property to docs

---

packages/react-swipeable-views-core/src/getDisplaySameSlide.js
packages/react-swipeable-views-core/src/getDisplaySameSlide.test.js

Close #440
Close #476
Close #498

Fix get display same slide

---

docs/src/pages/demos/demos.md

Notice user that he might have to add enableMouseEvents prop

---

packages/react-swipeable-views/src/SwipeableViews.js

check if an event is cancelable before preventDefault

---

packages/react-swipeable-views/src/SwipeableViews.js

Fix references to dom-helpers

---

docs/src/pages/demos/DemoAnimateHeight.js
packages/react-swipeable-views/src/SwipeableViews.js
packages/react-swipeable-views/src/SwipeableViews.test.js
packages/react-swipeable-views/src/index.js

Remove legacy context

---

packages/react-swipeable-views-core/package.json
packages/react-swipeable-views-utils/package.json

fix: `core` and `utils` should include `react` in `peerDependencies` too
